sudo: required
dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
install:
# Install conan
- sudo pip install --upgrade pip --user
- sudo pip install conan --user
# Automatic detection of your arch, compiler, etc.
- conan user
script:
# Download dependencies and build project
- conan install .
# Call your build system
- cmake . -G "Unix Makefiles"
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -upedanticcoder:$BINTRAY_API_KEY "https://api.bintray.com/content/pedanticcoder/otus-cpp/range/$TRAVIS_BUILD_NUMBER/range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
